model_name: "p-prodec2-modular-variable-pytorch"
model_type: "p-nd-np"
version: "2.0g"
has_meta_data: false # true
train_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/output2.json"]
validation_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/output2.json"]
test_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/output2.json"] #["../../datasets/SAT/M0-4SAT-100"] #["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/sat-race-test.json"] # ["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/3SAT-100"] #
model_path: "/Users/zhangziwei/workspace/python/PDP-Solver/Trained-models/SAT/p-prodec2-modular-variable-pytorch/2.0g/best/"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 150  # 110
mem_hidden_dim: 100
agg_hidden_dim: 100  # 135
mem_agg_hidden_dim: 150  # 50  =hidden_dimension
classifier_dim: 50  # 100
batch_size: 5000
learning_rate: 0.0001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 200
max_cache_size: 10000
dropout: 0.2
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 3500000
test_batch_limit: 40000000
generator: "v-modular"
min_n: 5
max_n: 100
min_alpha: 5
max_alpha: 10
min_k: 2
max_k: 10
min_q: 0.8
max_q: 0.9
min_c: 10
max_c: 20
local_search_iteration: 0
epsilon: 0.5
tolerance: 0.02
t_max: 10
lambda: 1
